services:
  app:
    build: .
    image: docker-demo-app:${VERSION:-1.0.0}
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
        monitor: 30s
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 60s
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production